import type { Metadata } from "next";
import { ClerkProvider, currentUser } from "@clerk/nextjs";
import { Inter } from "next/font/google";
import "./globals.css";
import SideNav from "@/components/shared/sideNav/SideNav";
import Topbar from "@/components/shared/topBar/Topbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shrinkify",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await currentUser();
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className} bg-dark-1`}>
          <div>
            <div className='layout_main'>
              <div className="layout_primary">
              <Topbar userId={user?.id || ''} />
              </div>
              <div className="Layout_wrapper">
              {children}
              </div>
            </div>
            <SideNav />
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
